name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4.1.5

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32z1 ccache autoconf git zip libyaml-dev
        wget https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--glibc--bleeding-edge-2021.11-1.tar.bz2 \
        && sudo mkdir -p /opt/toolchains \
        && sudo tar -xjf armv7-eabihf--glibc--bleeding-edge-2021.11-1.tar.bz2 -C /opt/toolchains \
        && rm armv7-eabihf--glibc--bleeding-edge-2021.11-1.tar.bz2
    - name: Configure Build Parameters
      run: |
        export ARCH=arm
        export NO_YAML=1
        bash bbuild-anykernel.sh klte
    - name: Uploading Kernel 
      run: |
        cp out/arch/arm/boot/zImage /home/runner/work/output/
        cp out/arch/arm/boot/dt.img /home/runner/work/output/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zImage
        path: /home/runner/work/output/zImage
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dtb
        path: /home/runner/work/output/dt.img
